<a href="https://colab.research.google.com/github/simrant27/LearningGAN/blob/main/UpSampling2D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Upsampling2D

In [3]:
from numpy import asarray
from keras.models import Sequential
from keras.layers import UpSampling2D, Dense, Reshape, Conv2DTranspose

In [ ]:
X = asarray([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [ ]:
X= X.reshape((1,2,2,1))
print(X)

[[[[1]
   [2]]

  [[3]
   [4]]]]


In [ ]:
model = Sequential()
model.add(UpSampling2D(input_shape = (2,2,1)))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/up_sampling2d.py:72: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ up_sampling2d_3 (UpSampling2D)  │ (None, 4, 4, 1)        │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
yhat = model.predict(X)
print(yhat)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step
[[[[1.]
   [1.]
   [2.]
   [2.]]

  [[1.]
   [1.]
   [2.]
   [2.]]

  [[3.]
   [3.]
   [4.]
   [4.]]

  [[3.]
   [3.]
   [4.]
   [4.]]]]


In [ ]:
yhat = yhat.reshape(4,4)
print(yhat)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


# Simple GAN model with UpSampling2D layer

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Reshape, UpSampling2D, Conv2D

In [ ]:
model = Sequential()
model.add(Dense(128 * 5 *5 , input_dim = 100))

model.add(Reshape((5,5,128)))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.add(UpSampling2D())

In [ ]:
model.add(Conv2D(1, (3,3), padding = 'same'))

model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 3200)           │       323,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape (Reshape)               │ (None, 5, 5, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ up_sampling2d_4 (UpSampling2D)  │ (None, 10, 10, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 10, 10, 1)      │         1,153 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 324,353 (1.24 MB)

 Trainable params: 324,353 (1.24 MB)

 Non-trainable params: 0 (0.00 B)

# Transpose Convolutional Layer

In [ ]:
from numpy import asarray
from keras.models import Sequential
from keras.layers import Conv2DTranspose

In [ ]:
X = asarray([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [ ]:
X = X.reshape((1,2,2,1))

In [ ]:
model = Sequential()
model.add(Conv2DTranspose(1,(1,1), strides = (2,2), input_shape = (2,2,1)))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv_transpose.py:94: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_transpose                │ (None, 4, 4, 1)        │             2 │
│ (Conv2DTranspose)               │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:

# define weights that they do nothing
weights = [asarray([[[[1]]]]), asarray([0])]
# store the weights in the
model.set_weights(weights)

In [ ]:
yhat = model.predict(X)

yhat = yhat.reshape((4,4))
print(yhat)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]


# Simple generator Model with Conv2DTrasnpose Layer

In [4]:
#model creation
model = Sequential()

#adding 1st layer
model.add(Dense(128 * 5 *5, input_dim = 100))

#reshape to 128 channel
model.add(Reshape((5,5,128)))

model.add(Conv2DTranspose(1, (3,3), strides = (2,2), padding = 'same'))
model.summary()


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 3200)           │       323,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape (Reshape)               │ (None, 5, 5, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_transpose                │ (None, 10, 10, 1)      │         1,153 │
│ (Conv2DTranspose)               │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 324,353 (1.24 MB)

 Trainable params: 324,353 (1.24 MB)

 Non-trainable params: 0 (0.00 B)